{
 "title": "Apache Spark - Performance Metrics Copy",
 "description": "Monitors spark metrics using Prometheus in Kubernetes",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Pod",
    "label": "Driver ID",
    "query": {
     "query": "label_values(kube_pod_info, pod)"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=\"$Pod\"}, node)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "query_result(kube_pod_status_phase{pod=\"$Pod\"})"
    }
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name=~\"$Pod\"},pod)"
    }
   },
   { "name": "copy_of_phase", "query": { "query": "" } },
   {
    "name": "copy_of_Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Direct Pool Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_DirectPoolMemory_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=\"driver\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalCores{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})"
    }
   ]
  },
  {
   "title": "Rdd Blocks",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "metrics_executor_rddBlocks{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}\r",
     "legendFormat": "{{ pod_name }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'$Pod'}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}  Transmitted"
    }
   ]
  },
  { "title": "Driver Resource  usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Driver Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 6 },
   "repeat": "Pod",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "\r\nmetrics_executor_memoryUsed_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=\"driver\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Driver Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "CPU Time" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_diskUsed_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=\"driver\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}",
     "legendFormat": "Used CPU : {{pod_name}}"
    }
   ]
  },
  {
   "title": "Driver GC : Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_totalGCTime_seconds_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=\"driver\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}"
    }
   ]
  },
  { "title": "Executor CPU /Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Executor :  Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "\r\nmetrics_executor_memoryUsed_bytes{application_id=~\".*\", application_name=\"Spark shell\", executor_id=~\"[0-9]\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}",
     "legendFormat": "{{pod_name}} "
    }
   ]
  },
  {
   "title": "Executor  :  Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "CPU Time" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_diskUsed_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\"[0-9]\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Executor GC : Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_totalGCTime_seconds_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\"[0-9]\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}"
    }
   ]
  },
  { "title": "Spark Shuffle metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Input Byte",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_totalInputBytes_bytes_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}}  Received"
    }
   ]
  },
  {
   "title": "Shuffle Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_totalShuffleWrite_bytes_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})",
     "legendFormat": "{{pod_name }}{{device}} Write"
    }
   ]
  },
  {
   "title": "Shuffle Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "metrics_executor_totalShuffleRead_bytes_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}",
     "legendFormat": "{{pod_name }} {{device}} Read"
    }
   ]
  },
  { "title": "Memory Heap / Non - Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_totalOnHeapStorageMemory_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(metrics_executor_usedOnHeapStorageMemory_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})",
     "legendFormat": " used"
    }
   ]
  },
  {
   "title": "Non Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_totalOffHeapStorageMemory_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(metrics_executor_usedOffHeapStorageMemory_bytes{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "Task metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total Task",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(metrics_executor_totalTasks_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})"
    }
   ]
  },
  {
   "title": "Completed Task",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_executor_completedTasks_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})"
    }
   ]
  },
  {
   "title": "Active Task",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nsum(metrics_executor_activeTasks{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"})",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Fail Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(metrics_executor_failedTasks_total{application_id=~\"application.*\", application_name=\"Spark shell\", executor_id=~\".*\", instance=\"10.0.0.11:4040\", job=\"spark-executors\"}[1m])"
    }
   ]
  }
 ]
}